development: &sqlite
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000

test:
    <<: *sqlite
    database: db/test.sqlite3

staging: &mysql
    adapter: mysql
    encoding: utf8
    socket: /tmp/mysql.sock
    username: root
    password:
    database: staging

production:
    <<: *mysql
    database: production