#
# Default application settings to be loaded during installation:
#
#   rake edss:settings:load
#   rake edss:settings:show
#

# Base URL.
#------------------------------------------------------------------------------
# Leave base_url blank if Fat Free CRM has been deployed in root URL, otherwise
# specify subdirectory. For example, when deployed to:
#
# http://www.domain.com       => :base_url: ""       # (leave blank)
# http://crm.domain.com       => :base_url: ""       # (leave blank)
# http://www.domain.com/crm   => :base_url: "/crm"   # (without trailing slash)
# http://www.domain.com/a/crm => :base_url: "/a/crm" # (without trailing slash)
:base_url: ""

# Locale.
#------------------------------------------------------------------------------
# Default locale is American English.
:locale: "en-US"

# User Signup.
#------------------------------------------------------------------------------
# The following setting controls user signup. Possible values are:
#   :allowed        -- users can sign up and use the system once they have registered.
#   :not_allowed    -- users can only be added by system administrator. This is the default.
#   :needs_approval -- users can sign up but must be approved before they can use the system.
:user_signup: :allowed

# Default View
#------------------------------------------------------------------------------
# Config first screen for center panel
#   :position_table -- show all position in table
#   :position_map    -- show all position in map
:default_view: :position_map

# Set howmany position in one table page
#------------------------------------------------------------------------------
:page_size: 20

# Class of Department
:department_class: ['หน่วยงานราชการสังกัดกรุงเทพมหานคร',
  'หน่วยงานราชการ',
  'หน่วยงานเอกชน',
  'มูลนิธิ',
  'องกรค์การกุศล',
  'หน่วยงานภาคประชาชน',
  'หน่วยงานในราชสำนัก',
  'หน่วยงานจากต่างชาติ',
  'อื่นๆ']

# Main and Admin Tabs.
#------------------------------------------------------------------------------
:tabs: [
  { :active : true,  :text : :tab_dashboard,     :url : { :controller : "/"              } },
  { :active : false, :text : :tab_tasks,         :url : { :controller : "tasks"          } },
  { :active : false, :text : :tab_campaigns,     :url : { :controller : "campaigns"      } },
  { :active : false, :text : :tab_leads,         :url : { :controller : "leads"          } },
  { :active : false, :text : :tab_accounts,      :url : { :controller : "accounts"       } },
  { :active : false, :text : :tab_contacts,      :url : { :controller : "contacts"       } },
  { :active : false, :text : :tab_opportunities, :url : { :controller : "opportunities"  } }
]

:admin_tabs: [
  { :active : true,  :text : :admin_tab_users,    :url : { :controller : "admin/users"    } },
  { :active : false, :text : :admin_tab_settings, :url : { :controller : "admin/settings" } },
  { :active : false, :text : :admin_tab_plugins,  :url : { :controller : "admin/plugins"  } }
]

# Campaign Status.
#------------------------------------------------------------------------------
campaign_status:
  - :planned
  - :started
  - :completed
  - :on_hold
  - :called_off

campaign_status_color:
  :planned    : palegreen
  :started    : paleturquoise
  :completed  : bisque
  :on_hold    : pink
  :called_off : thistle

# Lead Status and Source.
#------------------------------------------------------------------------------
lead_status:
  - :new
  - :contacted
  - :converted
  - :rejected

lead_status_color:
  :new       : palegreen
  :contacted : paleturquoise
  :converted : bisque
  :rejected  : thistle

lead_source:
  - :campaign
  - :cold_call
  - :conference
  - :online
  - :referral
  - :self
  - :web
  - :word_of_mouth
  - :other

# Opportunity Stage.
#------------------------------------------------------------------------------
opportunity_stage:
  - :prospecting
  - :analysis
  - :presentation
  - :proposal
  - :negotiation
  - :final_review
  - :won
  - :lost
  - "Custom"

opportunity_stage_color:
  :prospecting  : lavender
  :analysis     : mistyrose
  :presentation : wheat
  :proposal     : thistle
  :negotiation  : skyblue
  :final_review : aquamarine
  :won          : lightgreen
  :lost         : pink

# Task Category, Due Date, and Completed Date.
#------------------------------------------------------------------------------
task_category:
  - :call
  - :email
  - :follow_up
  - :lunch
  - :meeting
  - :money
  - :presentation
  - :trip

task_category_color:
  :call         : lavender
  :email        : paleturquoise
  :follow_up    : mistyrose
  :lunch        : wheat
  :meeting      : thistle
  :money        : lightgreen
  :presentation : aquamarine
  :trip         : skyblue

task_bucket:
  - :overdue
  - :due_asap
  - :due_today
  - :due_tomorrow
  - :due_this_week
  - :due_next_week
  - :due_later

task_completed:
  - :completed_today
  - :completed_yesterday
  - :completed_last_week
  - :completed_this_month
  - :completed_last_month
